[SITE-1585] Move check-commits into GitHub actions (#146)
* just add a step that runs the script
this may or may not work depending on how GHA sources files, but we'll start here

* specify the path

* run a git fetch before running the script

* check out default branch so we have a local copy

* check out a local copy of default

* don't warn about detached head

* allow changes to ci.yml

* remove `variable`

* create a failure status artifact
don't run playwright tests if ci failed

* don't create a status file if it already exists

* create an aggregate status file

* use the same php-version matrix

* remove aggregate status

* pull and aggregate all statuses

* update perms and add logging

* trigger on workflow dispatch

* remove status checks

* trigger workflow on success

* add token

* re-add the status artifacts

* go back to running on PR

* wait for the status artifacts and check them before running the tests

* remove test job

* add missing done

* add some debugging code

* make the files unique

* allow gh run download to fail

* upload the artifacts

* add a comment when we're done checking the linting status

* comment on the PR

* update permissions

* exclude status check files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,8 @@ on:
 
 permissions:
     contents: write
+    actions: read
+    pull-requests: write
 
 jobs:
   build:
@@ -36,6 +38,24 @@ jobs:
         key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
         restore-keys: ${{ runner.os }}-composer-
 
+    - name: Check Commits
+      run: |
+        # Don't warn about detached head.
+        git config advice.detachedHead false
+        git fetch --all
+        git checkout -b default origin/default
+        git checkout ${{ github.event.pull_request.head.sha }}
+        echo "This script does preliminary checks to make sure that the commits in a PR made in this repository are ready for the deploy-public-upstream script. i.e. any given commit modifies either 'normal' or 'non-release' files, never mixed."
+        bash ${{ github.workspace }}/devops/scripts/check-commits.sh || echo "commit_check_failed=1" >> $GITHUB_ENV
+
+    - name: Comment on PR if commit check failed
+      if: env.commit_check_failed == '1'
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh pr comment ${{ github.event.pull_request.number }} -b "Hi from your friendly robot! :robot: It looks like there might be commits to both release and non-release files in this PR. Please review and remove any commits that don't belong."
+        exit 1
+
     - name: Check Composer lock file is up to date
       run: composer validate --no-check-all
 
@@ -58,3 +78,25 @@ jobs:
         CI: 1
       run: |
           bats -p -t .github/tests
+
+    - name: Create failure status artifact
+      if: failure()
+      run: |
+        # In the case of a failure, remove the previous status, whatever it was, and update it to 1.
+        if [ -f status-${{ matrix.php-version }}-${{ github.sha }}.txt ]; then
+          rm status-${{ matrix.php-version }}-${{ github.sha }}.txt
+        fi
+        echo "1" > status-${{ matrix.php-version }}-${{ github.sha }}.txt
+    - name: Create success status artifact
+      if: success()
+      run: |
+        # Only create a status file if it doesn't already exist.
+        if [ ! -f status-${{ matrix.php-version }}-${{ github.sha }}.txt ]; then
+          echo "0" > status-${{ matrix.php-version }}-${{ github.sha }}.txt
+        fi
+
+    - name: Upload status artifacts
+      uses: actions/upload-artifact@v4
+      with:
+        name: status-${{ matrix.php-version }}-${{ github.sha }}
+        path: status-${{ matrix.php-version }}-${{ github.sha }}.txt
