[SITE-1585] Move check-commits into GitHub actions (#146)
* just add a step that runs the script
this may or may not work depending on how GHA sources files, but we'll start here

* specify the path

* run a git fetch before running the script

* check out default branch so we have a local copy

* check out a local copy of default

* don't warn about detached head

* allow changes to ci.yml

* remove `variable`

* create a failure status artifact
don't run playwright tests if ci failed

* don't create a status file if it already exists

* create an aggregate status file

* use the same php-version matrix

* remove aggregate status

* pull and aggregate all statuses

* update perms and add logging

* trigger on workflow dispatch

* remove status checks

* trigger workflow on success

* add token

* re-add the status artifacts

* go back to running on PR

* wait for the status artifacts and check them before running the tests

* remove test job

* add missing done

* add some debugging code

* make the files unique

* allow gh run download to fail

* upload the artifacts

* add a comment when we're done checking the linting status

* comment on the PR

* update permissions

* exclude status check files

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -9,14 +9,66 @@ on:
 
 permissions:
     contents: write
+    actions: read
 
 jobs:
+
   playwright-single:
     name: Single site
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Wait for status artifacts
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          max_attempts=10
+          delay_seconds=30
+          attempt=0
+          success=0
+          status=0
+
+          echo "Checking for status artifacts..."
+
+          while [ $attempt -lt $max_attempts ]; do
+            # Attempt to download the artifacts.
+            gh run download -n status-8.1-${{ github.sha }} || true
+            gh run download -n status-8.2-${{ github.sha }} || true
+            gh run download -n status-8.3-${{ github.sha }} || true
+
+            if [ -f status-8.1-${{ github.sha }}.txt ] && [ -f status-8.2-${{ github.sha }}.txt ] && [ -f status-8.3-${{ github.sha }}.txt ]; then
+              success=1
+              break
+            else
+              echo "Status files not found. Sleeping for $delay_seconds seconds..."
+              sleep $delay_seconds
+            fi
+            attempt=$(( attempt + 1 ))
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Timed out waiting for status artifacts."
+            exit 1
+          fi
+
+          for file in status-*.txt; do
+            status=$(cat $file)
+            if [ $status -eq 1 ]; then
+              echo "status=$status" >> $GITHUB_ENV
+              exit 1
+            fi
+          done
+
+          echo "Linting tests passed. Proceeding with Playwright tests. ✅"
+          echo "status=$status" >> $GITHUB_ENV
+
+      - name: Linting failed
+        if: env.status == '1'
+        run: |
+          echo "One or more jobs in a previous workflow failed. Exiting."
+          exit 1
 
       - name: Get last commit message
         env:
@@ -97,6 +149,54 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Wait for status artifacts
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          max_attempts=10
+          delay_seconds=30
+          attempt=0
+          success=0
+          status=0
+
+          echo "Checking for status artifacts..."
+
+          while [ $attempt -lt $max_attempts ]; do
+            # Attempt to download the artifacts.
+            gh run download -n status-8.1-${{ github.sha }} || true
+            gh run download -n status-8.2-${{ github.sha }} || true
+            gh run download -n status-8.3-${{ github.sha }} || true
+
+            if [ -f status-8.1-${{ github.sha }}.txt ] && [ -f status-8.2-${{ github.sha }}.txt ] && [ -f status-8.3-${{ github.sha }}.txt ]; then
+              success=1
+              break
+            else
+              echo "Status files not found. Sleeping for $delay_seconds seconds..."
+              sleep $delay_seconds
+            fi
+            attempt=$(( attempt + 1 ))
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Timed out waiting for status artifacts."
+            exit 1
+          fi
+
+          for file in status-*.txt; do
+            status=$(cat $file)
+            if [ $status -eq 1 ]; then
+              echo "status=$status" >> $GITHUB_ENV
+              exit 1
+            fi
+          done
+          echo "status=$status" >> $GITHUB_ENV
+
+      - name: Linting failed
+        if: env.status == '1'
+        run: |
+          echo "One or more jobs in a previous workflow failed. Exiting."
+          exit 1
 
       - name: Get last commit message
         env:
@@ -182,6 +282,54 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Wait for status artifacts
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          max_attempts=10
+          delay_seconds=30
+          attempt=0
+          success=0
+          status=0
+
+          echo "Checking for status artifacts..."
+
+          while [ $attempt -lt $max_attempts ]; do
+            # Attempt to download the artifacts.
+            gh run download -n status-8.1-${{ github.sha }} || true
+            gh run download -n status-8.2-${{ github.sha }} || true
+            gh run download -n status-8.3-${{ github.sha }} || true
+
+            if [ -f status-8.1-${{ github.sha }}.txt ] && [ -f status-8.2-${{ github.sha }}.txt ] && [ -f status-8.3-${{ github.sha }}.txt ]; then
+              success=1
+              break
+            else
+              echo "Status files not found. Sleeping for $delay_seconds seconds..."
+              sleep $delay_seconds
+            fi
+            attempt=$(( attempt + 1 ))
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Timed out waiting for status artifacts."
+            exit 1
+          fi
+
+          for file in status-*.txt; do
+            status=$(cat $file)
+            if [ $status -eq 1 ]; then
+              echo "status=$status" >> $GITHUB_ENV
+              exit 1
+            fi
+          done
+          echo "status=$status" >> $GITHUB_ENV
+
+      - name: Linting failed
+        if: env.status == '1'
+        run: |
+          echo "One or more jobs in a previous workflow failed. Exiting."
+          exit 1
 
       - name: Get last commit message
         env:
