wait for the status artifacts and check them before running the tests

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -25,6 +25,53 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
+      - name: Wait for status artifacts
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          max_attempts=10
+          delay_seconds=30
+          attempt=0
+          success=0
+          status=0
+
+          echo "Checking for status artifacts..."
+
+          while [ $attempt -lt $max_attempts ]; do
+            # Attempt to download the artifacts.
+            gh run download -n status-8.1
+            gh run download -n status-8.2
+            gh run download -n status-8.3
+
+            if [ -f status-8.1.txt ] && [ -f status-8.2.txt ] && [ -f status-8.3.txt ]; then
+              success=1
+              break
+            else
+              echo "Status files not found. Sleeping for $delay_seconds seconds..."
+              sleep $delay_seconds
+            fi
+            attempt=$(( attempt + 1 ))
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Timed out waiting for status artifacts."
+            exit 1
+          fi
+
+          for file in status-*.txt; do
+            status=$(cat $file)
+            if [ $status -eq 1 ]; then
+              echo "status=$status" >> $GITHUB_ENV
+              exit 1
+            fi
+          echo "status=$status" >> $GITHUB_ENV
+
+      - name: Linting failed
+        if: env.status == '1'
+        run: |
+          echo "One or more jobs in a previous workflow failed. Exiting."
+          exit 1
+
       - name: Get last commit message
         env:
           GH_TOKEN: ${{ github.token }}
@@ -104,6 +151,53 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Wait for status artifacts
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          max_attempts=10
+          delay_seconds=30
+          attempt=0
+          success=0
+          status=0
+
+          echo "Checking for status artifacts..."
+
+          while [ $attempt -lt $max_attempts ]; do
+            # Attempt to download the artifacts.
+            gh run download -n status-8.1
+            gh run download -n status-8.2
+            gh run download -n status-8.3
+
+            if [ -f status-8.1.txt ] && [ -f status-8.2.txt ] && [ -f status-8.3.txt ]; then
+              success=1
+              break
+            else
+              echo "Status files not found. Sleeping for $delay_seconds seconds..."
+              sleep $delay_seconds
+            fi
+            attempt=$(( attempt + 1 ))
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Timed out waiting for status artifacts."
+            exit 1
+          fi
+
+          for file in status-*.txt; do
+            status=$(cat $file)
+            if [ $status -eq 1 ]; then
+              echo "status=$status" >> $GITHUB_ENV
+              exit 1
+            fi
+          echo "status=$status" >> $GITHUB_ENV
+
+      - name: Linting failed
+        if: env.status == '1'
+        run: |
+          echo "One or more jobs in a previous workflow failed. Exiting."
+          exit 1
 
       - name: Get last commit message
         env:
@@ -189,6 +283,47 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+
+      - name: Wait for status artifacts
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          max_attempts=10
+          delay_seconds=30
+          attempt=0
+          success=0
+          status=0
+
+          echo "Checking for status artifacts..."
+
+          while [ $attempt -lt $max_attempts ]; do
+            # Attempt to download the artifacts.
+            gh run download -n status-8.1
+            gh run download -n status-8.2
+            gh run download -n status-8.3
+
+            if [ -f status-8.1.txt ] && [ -f status-8.2.txt ] && [ -f status-8.3.txt ]; then
+              success=1
+              break
+            else
+              echo "Status files not found. Sleeping for $delay_seconds seconds..."
+              sleep $delay_seconds
+            fi
+            attempt=$(( attempt + 1 ))
+          done
+
+          if [ $success -eq 0 ]; then
+            echo "Timed out waiting for status artifacts."
+            exit 1
+          fi
+
+          for file in status-*.txt; do
+            status=$(cat $file)
+            if [ $status -eq 1 ]; then
+              echo "status=$status" >> $GITHUB_ENV
+              exit 1
+            fi
+          echo "status=$status" >> $GITHUB_ENV
 
       - name: Linting failed
         if: env.status == '1'
